# Form implementation generated from reading ui file 'voting_gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 400)
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(20, 40, 41, 71))
        self.id_label.setMinimumSize(QtCore.QSize(0, 0))
        self.id_label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(140, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setScaledContents(False)
        self.title_label.setObjectName("title_label")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(10, 310, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.john_radiobutton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.john_radiobutton.setGeometry(QtCore.QRect(40, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.john_radiobutton.setFont(font)
        self.john_radiobutton.setObjectName("john_radiobutton")
        self.jane_radiobutton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jane_radiobutton.setGeometry(QtCore.QRect(40, 170, 95, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.jane_radiobutton.setFont(font)
        self.jane_radiobutton.setObjectName("jane_radiobutton")
        self.candidate_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidate_label.setGeometry(QtCore.QRect(10, 130, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.candidate_label.setFont(font)
        self.candidate_label.setObjectName("candidate_label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 60, 261, 31))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.id_label.setText(_translate("MainWindow", "ID"))
        self.title_label.setText(_translate("MainWindow", "Voting"))
        self.submit_button.setText(_translate("MainWindow", "Submit Vote"))
        self.john_radiobutton.setText(_translate("MainWindow", "John"))
        self.jane_radiobutton.setText(_translate("MainWindow", "Jane"))
        self.candidate_label.setText(_translate("MainWindow", "Choose Candidates"))
